package heif

import (
	"image"
)

// Generated by gen.sh. DO NOT EDIT.

func init() {
	image.RegisterFormat("heic", "????ftypheic", Decode, DecodeConfig)
	image.RegisterFormat("heix", "????ftypheix", Decode, DecodeConfig)
	image.RegisterFormat("hevc", "????ftyphevc", Decode, DecodeConfig)
	image.RegisterFormat("hevx", "????ftyphevx", Decode, DecodeConfig)
	image.RegisterFormat("heim", "????ftypheim", Decode, DecodeConfig)
	image.RegisterFormat("heis", "????ftypheis", Decode, DecodeConfig)
	image.RegisterFormat("hevm", "????ftyphevm", Decode, DecodeConfig)
	image.RegisterFormat("hevs", "????ftyphevs", Decode, DecodeConfig)
	image.RegisterFormat("avif", "????ftypavif", Decode, DecodeConfig)
	image.RegisterFormat("avis", "????ftypavis", Decode, DecodeConfig)
	image.RegisterFormat("mif1", "????ftypmif1", Decode, DecodeConfig)
	image.RegisterFormat("mif2", "????ftypmif2", Decode, DecodeConfig)
	image.RegisterFormat("msf1", "????ftypmsf1", Decode, DecodeConfig)
	image.RegisterFormat("vvic", "????ftypvvic", Decode, DecodeConfig)
	image.RegisterFormat("vvis", "????ftypvvis", Decode, DecodeConfig)
	image.RegisterFormat("evbi", "????ftypevbi", Decode, DecodeConfig)
	image.RegisterFormat("evmi", "????ftypevmi", Decode, DecodeConfig)
	image.RegisterFormat("evbs", "????ftypevbs", Decode, DecodeConfig)
	image.RegisterFormat("evms", "????ftypevms", Decode, DecodeConfig)
	image.RegisterFormat("jpeg", "????ftypjpeg", Decode, DecodeConfig)
	image.RegisterFormat("jpgs", "????ftypjpgs", Decode, DecodeConfig)
	image.RegisterFormat("j2ki", "????ftypj2ki", Decode, DecodeConfig)
	image.RegisterFormat("j2is", "????ftypj2is", Decode, DecodeConfig)
	image.RegisterFormat("miaf", "????ftypmiaf", Decode, DecodeConfig)
	image.RegisterFormat("1pic", "????ftyp1pic", Decode, DecodeConfig)
}
